#!/bin/bash
# Generates a .env file for game-backlog.
#
# Standalone (local dev):
#   ./scripts/generate-env.sh
#
# Called by setup-pi.sh (Pi deployment):
#   ./scripts/generate-env.sh \
#     --env prod \
#     --port 4001 \
#     --hostname pi4.tail1234.ts.net \
#     --dev-prefix dev \
#     --client-id <uuid> \
#     --client-secret <hex>
#
# Flags:
#   --env           prod|dev          (default: development)
#   --port          PORT              (default: 3000)
#   --hostname      Tailscale hostname (default: localhost)
#   --dev-prefix    dev path prefix   (default: dev)
#   --client-id     shared OAuth client ID with account-manager
#   --client-secret shared OAuth client secret with account-manager
#   --force         overwrite existing .env

set -e

# ── Defaults (local dev) ─────────────────────────────────────────────────────
ENV=development
PORT=3001                 # gamebacklog's own port
ACCOUNT_MANAGER_PORT=3000 # account-manager's port (local dev only)
HOSTNAME=localhost
DEV_PREFIX=dev
CLIENT_ID=
CLIENT_SECRET=
OUTPUT=
FORCE=false

# ── Parse flags ──────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)                  ENV="$2";                  shift 2 ;;
    --port)                 PORT="$2";                 shift 2 ;;
    --account-manager-port) ACCOUNT_MANAGER_PORT="$2"; shift 2 ;;
    --hostname)             HOSTNAME="$2";             shift 2 ;;
    --dev-prefix)           DEV_PREFIX="$2";           shift 2 ;;
    --client-id)            CLIENT_ID="$2";            shift 2 ;;
    --client-secret)        CLIENT_SECRET="$2";        shift 2 ;;
    --output)               OUTPUT="$2";               shift 2 ;;
    --force)                FORCE=true;                shift   ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
done

# ── Resolve output path ───────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -n "$OUTPUT" ]]; then
  ENV_FILE="$OUTPUT"
else
  ENV_FILE="${SCRIPT_DIR}/../.env"
fi

if [[ -f "$ENV_FILE" ]] && [[ "$FORCE" != "true" ]]; then
  echo ".env already exists at ${ENV_FILE}. Pass --force to overwrite." >&2
  exit 0
fi

# ── Derive URLs from hostname ────────────────────────────────────────────────
if [[ "$HOSTNAME" == "localhost" ]]; then
  # Local dev: each service on its own port, no path prefix
  ACCOUNT_MANAGER_URL="http://localhost:${ACCOUNT_MANAGER_PORT}"
  ACCOUNT_MANAGER_ISSUER="http://localhost:${ACCOUNT_MANAGER_PORT}"
  REDIRECT_URI="http://localhost:${PORT}/auth/callback"
  VITE_ACCOUNT_MANAGER_URL="http://localhost:${ACCOUNT_MANAGER_PORT}"
  PUBLIC_KEY_PATH="../account-manager/data/keys/public.pem"
  DATA_DIR="./data"
elif [[ "$ENV" == "production" || "$ENV" == "prod" ]]; then
  ACCOUNT_MANAGER_URL="https://${HOSTNAME}/account-manager"
  ACCOUNT_MANAGER_ISSUER="https://${HOSTNAME}/account-manager"
  REDIRECT_URI="https://${HOSTNAME}/gamebacklog/auth/callback"
  VITE_ACCOUNT_MANAGER_URL="https://${HOSTNAME}/account-manager"
  PUBLIC_KEY_PATH="/opt/prod/account-manager/data/keys/public.pem"
  DATA_DIR="/var/lib/gamebacklog-prod"
else
  ACCOUNT_MANAGER_URL="https://${HOSTNAME}/${DEV_PREFIX}/account-manager"
  ACCOUNT_MANAGER_ISSUER="https://${HOSTNAME}/${DEV_PREFIX}/account-manager"
  REDIRECT_URI="https://${HOSTNAME}/${DEV_PREFIX}/gamebacklog/auth/callback"
  VITE_ACCOUNT_MANAGER_URL="https://${HOSTNAME}/${DEV_PREFIX}/account-manager"
  PUBLIC_KEY_PATH="/opt/dev/account-manager/data/keys/public.pem"
  DATA_DIR="/var/lib/gamebacklog-dev"
fi

# ── Generate secrets ─────────────────────────────────────────────────────────
gen_hex() { openssl rand -hex "$1"; }
gen_uuid() { python3 -c "import uuid; print(uuid.uuid4())"; }

CSRF_SECRET="$(gen_hex 32)"
[[ -z "$CLIENT_ID" ]]     && CLIENT_ID="$(gen_uuid)"
[[ -z "$CLIENT_SECRET" ]] && CLIENT_SECRET="$(gen_hex 32)"

# ── Write .env ───────────────────────────────────────────────────────────────
cat > "$ENV_FILE" << EOF
# Generated by scripts/generate-env.sh on $(date)
# NEVER commit this file to git.

PORT=${PORT}
NODE_ENV=${ENV}
DATA_DIR=${DATA_DIR}

# Strong random secret for CSRF protection
CSRF_SECRET=${CSRF_SECRET}

# Account Manager — auth issuer for JWT verification and OAuth flows
ACCOUNT_MANAGER_URL=${ACCOUNT_MANAGER_URL}
ACCOUNT_MANAGER_ISSUER=${ACCOUNT_MANAGER_ISSUER}

# Path to account-manager's RSA public key (RS256 token verification)
PUBLIC_KEY_PATH=${PUBLIC_KEY_PATH}

# OAuth client registered in account-manager for the game backlog PKCE flow.
# GAMEBACKLOG_CLIENT_ID and GAMEBACKLOG_CLIENT_SECRET must match the values
# in account-manager's .env exactly.
GAMEBACKLOG_CLIENT_ID=${CLIENT_ID}
GAMEBACKLOG_CLIENT_SECRET=${CLIENT_SECRET}
GAMEBACKLOG_REDIRECT_URI=${REDIRECT_URI}

# Exposed to the frontend build (Vite replaces at build time)
VITE_ACCOUNT_MANAGER_URL=${VITE_ACCOUNT_MANAGER_URL}
EOF

echo ".env written to ${ENV_FILE}"
echo ""
echo "Shared values (copy these to account-manager's .env):"
echo "  GAMEBACKLOG_CLIENT_ID=${CLIENT_ID}"
echo "  GAMEBACKLOG_CLIENT_SECRET=${CLIENT_SECRET}"
echo "  GAMEBACKLOG_REDIRECT_URI=${REDIRECT_URI}"
